test pest debug output

diff --git a/.github/workflows/laravel.yml b/.github/workflows/laravel.yml
--- a/.github/workflows/laravel.yml
+++ b/.github/workflows/laravel.yml
@@ -62,8 +62,8 @@ jobs:
         DB_USERNAME: root
         DB_PASSWORD: password
       run: |
-          vendor/bin/pest --testdox > test-summary.txt || true
-          echo "TEST_EXIT_CODE=$?" >> $GITHUB_ENV
+        vendor/bin/pest --testdox || echo "Pest tests failed with exit code $?"
+        echo "TEST_EXIT_CODE=$?" >> $GITHUB_ENV
     - name: Comment PR on Test Result
       if: always() && github.event_name == 'pull_request'
       uses: actions/github-script@v5
